name: Build UI for Netlify
on:
  push:
    branches:
      - master
    paths-ignore:
      - "LAST_UPDATED"
      - "data.json"
      - "data.js"
      - "data-es.js"
      - "tags.txt"
      - "tags-prefix.txt"
      - "_redirect-out"
      - "package.json"

jobs:
  install-deps:
    if: github.repository == 'phpid-jakarta/phpid-learning'
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install locked dependencies
        run: yarn install --frozen-lockfile

      - name: Generate file json
        run: yarn toJson

      - name: Update export script on package.json
        run: yarn toTags

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Cache dependencies
        uses: actions/cache@v1
        id: cache-deps
        with:
          path: "."
          key: ${{ github.sha }}

  build_ui:
    if: github.repository == 'phpid-jakarta/phpid-learning'
    needs: install-deps
    runs-on: ubuntu-latest
    name: Export to Static
    steps:
      - name: Restore cached dependencies
        uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Perform export to static
        run: yarn export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./__sapper__/export
          publish_branch: netlify-pages

  json_data:
    if: github.repository == 'phpid-jakarta/phpid-learning'
    needs: install-deps
    runs-on: ubuntu-latest
    name: Push JSON Data
    steps:
      - name: Restore cached dependencies
        uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./api
          publish_branch: api

      # - name: Perform push JSON data to master
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: '${{ secrets.PERSONAL_TOKEN }}'
      #     force: true

